name: Build on Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install MSYS2
      run: choco install msys2

    - name: Build in MinGW
      env:
        MSYSTEM: MINGW64
      run: |
        c:\tools\msys64\usr\bin\bash -l -c "scripts/build-mingw.sh"
